name: 'New-Module'
description: 'Create repos for a new PowerShell module that uses the PSModule framework'
branding:
  icon: activity
  color: blue

inputs:
  Message:
    description: 'A message to test with.'
    required: false
    default: 'Hello World!'
  Verbose:
    description: 'Enable verbose output.'
    required: false
    default: 'false'
  WhatIf:
    description: 'Run in WhatIf mode.'
    required: false
    default: 'false'

runs:
  using: 'composite'
  steps:
    - name: Run New-Module
      shell: pwsh
      run: |
        Write-Output '::group::New-Module'
        Write-Output '-------------------------------------------'
        Write-Output 'Action inputs:'
        $params = @{
            Message = '${{ inputs.Message }}'
            Verbose = [System.Convert]::ToBoolean('${{ inputs.Verbose }}')
            WhatIf  = [System.Convert]::ToBoolean('${{ inputs.WhatIf }}')
        }
        $params.GetEnumerator() | Sort-Object -Property Name
        Write-Output '-------------------------------------------'
        . "$env:GITHUB_ACTION_PATH\scripts\main.ps1" @params
        Write-Output '-------------------------------------------'
        Write-Output '::endgroup::'
